### ISSUE TITLE
Utilising patterns in messages

### ISSUE THREAD

**Issue by astro-roro** [FlyingKiwis/Nina.DiscordAlert#6]
Love this addon! My only suggestions is it would be great to be able to use the file format patterns in NINA such as `$$TARGETNAME$$`, `$$FILTER$$`, etc. within the messages to give more context in discord pings.

**Comment by Croniac** [comment]
As an expansion to @RohanHinton suggestion above, this plug-in would benefit greatly by having many of the functions in Dale Ghent's "Ground Control".   I wonder if it might be worth @FlyingKiwis time to collab with him and integrate the two, rather than trying to re-invent?

The main draw for me to DiscordAlert plug in is that I'm pretty much always on discord.  So thank you for doing this.  But the extra functionality would be killer.

**Comment by FlyingKiwis** [comment]
Added in https://github.com/FlyingKiwis/Nina.DiscordAlert/releases/tag/v2.1.0

**Comment by astro-roro** [comment]
Amazing! So keen to try this out, thanks @FlyingKiwis
